export const mockEmployees = [
  {
    email: "john.doe@example.com",
    password: "password123",
    name: "John Doe",
    gender: "Male",
    role: "Engineer",
  },
  {
    email: "jane.smith@example.com",
    password: "securepass",
    name: "Jane Smith",
    gender: "Female",
    role: "Tester",
  },
  {
    email: "david.lee@example.com",
    password: "davidpass",
    name: "David Lee",
    gender: "Male",
    role: "Designer",
  },
  {
    email: "sarah.jones@example.com",
    password: "sarahspassword",
    name: "Sarah Jones",
    gender: "Female",
    role: "Quality Control",
  },
  {
    email: "michael.brown@example.com",
    password: "michaelpass",
    name: "Michael Brown",
    gender: "Male",
    role: "Fresher",
  },
  {
    email: "emily.wilson@example.com",
    password: "emilypass",
    name: "Emily Wilson",
    gender: "Female",
    role: "Intern",
  },
  {
    email: "kevin.nguyen@example.com",
    password: "kevinpass",
    name: "Kevin Nguyen",
    gender: "Male",
    role: "Engineer",
  },
  {
    email: "jessica.garcia@example.com",
    password: "jessicapass",
    name: "Jessica Garcia",
    gender: "Female",
    role: "Tester",
  },
  {
    email: "ryan.martinez@example.com",
    password: "ryanpass",
    name: "Ryan Martinez",
    gender: "Male",
    role: "Designer",
  },
  {
    email: "ashley.anderson@example.com",
    password: "ashleypass",
    name: "Ashley Anderson",
    gender: "Female",
    role: "Quality Control",
  },
  {
    email: "matthew.thomas@example.com",
    password: "matthewpass",
    name: "Matthew Thomas",
    gender: "Male",
    role: "Fresher",
  },
  {
    email: "olivia.jackson@example.com",
    password: "oliviapass",
    name: "Olivia Jackson",
    gender: "Female",
    role: "Intern",
  },
  {
    email: "william.white@example.com",
    password: "williampass",
    name: "William White",
    gender: "Male",
    role: "Engineer",
  },
  {
    email: "sophia.harris@example.com",
    password: "sophiapass",
    name: "Sophia Harris",
    gender: "Female",
    role: "Tester",
  },
  {
    email: "james.martin@example.com",
    password: "jamespass",
    name: "James Martin",
    gender: "Male",
    role: "Designer",
  },
  {
    email: "isabella.lewis@example.com",
    password: "isabellapass",
    name: "Isabella Lewis",
    gender: "Female",
    role: "Quality Control",
  },
  {
    email: "ethan.walker@example.com",
    password: "ethanpass",
    name: "Ethan Walker",
    gender: "Male",
    role: "Fresher",
  },
  {
    email: "mia.hall@example.com",
    password: "miapass",
    name: "Mia Hall",
    gender: "Female",
    role: "Intern",
  },
  {
    email: "alexander.young@example.com",
    password: "alexpass",
    name: "Alexander Young",
    gender: "Male",
    role: "Engineer",
  },
  {
    email: "abigail.king@example.com",
    password: "abigailpass",
    name: "Abigail King",
    gender: "Female",
    role: "Tester",
  },
];